### ISSUE TITLE
Spike: When publicly viewed, displays child/member works in a single viewer

### ISSUE THREAD

**Issue by jillpe** [notch8/essi#14]
# Summary
This was part of the SOW. We want to check if this is working.

# Accepted Criteria
- [ ] If this is working, close ticket. If this is not working, create follow up tickets and close this ticket

# Tested on staging

Viewing a public work shows all child/member works in a single viewer.
![image](https://user-images.githubusercontent.com/19597776/230982271-a603c1e3-b9e5-4c05-914b-7125b423e608.png)

NOTE: the child works in this work
![image](https://user-images.githubusercontent.com/19597776/230982441-dbe19752-3dbf-4923-b823-fa5d026c7afb.png)

**Comment by ShanaLMoore** [comment]
We believe this point is covered by installing iiif_print, as long as the work is public non admins should be able to see the same functionality.

**Comment by jlhardes** [comment]
All child member works are showing in the viewer and in the Items list for the following parent/child work: https://dcadmin-test.dlib.indiana.edu/concern/paged_resources/cn69m4128?locale=en
