### ISSUE TITLE
Spike: All child work thumbnails display in the items pane

### ISSUE THREAD

**Issue by jillpe** [notch8/essi#15]
# Summary
This was part of the SOW. We want to check if this is working.

# Accepted Criteria
- [ ] If this is working, close ticket. If this is not working, create follow up tickets and close this ticket

# Tested on staging

Thumbnails show in UV
![image](https://user-images.githubusercontent.com/19597776/230962325-836fa4f9-e40e-47f1-9c94-91978b1250aa.png)

**Comment by jlhardes** [comment]
This is working and showing all child work thumbnails for the following parent/child work: https://dcadmin-test.dlib.indiana.edu/concern/paged_resources/cn69m4128?locale=en
