### ISSUE TITLE
Spike: Individual child/member work metadata can be viewed in the “more information” tab, which currently only shows a subset of metadata. The initial requirement is for all publicly viewable (exposed) metadata to appear in the viewer. If display becomes too crowded, Indiana can add a tag to metadata they would like to appear in the viewer.

### ISSUE THREAD

**Issue by jillpe** [notch8/essi#16]
# Summary
This was part of the SOW. We want to check if this is working.

# Accepted Criteria
- [ ] If this is working, close ticket. If this is not working, create follow up tickets and close this ticket
- [ ] #20 (follow up ticket created)

**Comment by ShanaLMoore** [comment]
Essi previously had a configuration to say which metadata fields to display in the more information pane. subset metadata: https://github.com/scientist-softserv/essi/blob/main/config/essi_config.example.yml#L158-L172

ref PR: https://github.com/scientist-softserv/essi/commit/add8a0ace7745007c305579d56328934086e5353

https://github.com/scientist-softserv/essi/blob/main/lib/extensions/hyrax/work_show_presenter/manifest_metadata.rb#L31 

https://github.com/scientist-softserv/essi/blob/main/config/initializers/hyrax.rb#L189-L193

**Comment by laritakr** [comment]
Followup ticket was made.
