### ISSUE TITLE
Spike: Navigation tool to move to next child/member work (if possible)

### ISSUE THREAD

**Issue by jillpe** [notch8/essi#18]
# Summary
This was part of the SOW. We want to check if this is working.

# Accepted Criteria
- [ ] If this is working, close ticket. If this is not working, create follow up tickets and close this ticket

# Testing Staging

Navigation tool comes with UV:
![essi-nav](https://user-images.githubusercontent.com/19597776/230990648-199f9ac5-d2ed-4127-b9c8-15f355b389db.gif)

**Comment by jlhardes** [comment]
This is working on the test work I have created with parent/child works: https://dcadmin-test.dlib.indiana.edu/concern/paged_resources/cn69m4128?locale=en
