### ISSUE TITLE
Show Parents' matched results

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/essi#23]
# Summary

related and to be completed after

- #24

A user should have some kind of indication that a match was found, when searching for parent metadata in the UV.

Consider implementing highlighting in the UV, displaying something below it on the parent's show page, or having it behave the same way child metadata matches do.

# Acceptance Criteria

- [ ] Currently, if a user searches for valid parent metadata, it'll will not display any indication to show a match. We want to let the user know what metadata term resulted in a match. 

# Testing Instructions
TBD

# Notes

**Comment by laritakr** [comment]
TODO: Confirm that this is in scope with @jillpe

**Comment by ShanaLMoore** [comment]
This was confirmed by Rob. Ref notes: https://docs.google.com/document/d/1orq5ZIqKrJTr7Tt0EA1tYdb2vA1cnehkc7Z2cdCqkMI/edit#

It looks like it'll be completed as part of #24 He has it working the same way that child metadata matches do. It highlights the matching work with a blue magnifying glass, which I believe suffices for this ticket's ask.
