### ISSUE TITLE
Searching for parent metadata leads to error

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/essi#24]
# Summary

Searching for parent metadata leads to a No Matches Found error in the UV. 

# Related 
ref: #21 

Make sure that the work to enable searching for all metadata is enabled or included for your local development. ref: https://github.com/scientist-softserv/britishlibrary/pull/390

# Acceptance Criteria
If there is a parent match...
- [ ] We should not see the No Matches Found error
- [ ] the parent thumbnail should be highlighted with a blue magnifying glass, in the UV's left pane.

If there is no matches...
- [ ] we should see the No Matches Found error. 

# Screenshots or Video

Searched for the word "dog" which is the parent's Alt Title: 

![Image](https://user-images.githubusercontent.com/10081604/233639976-9e6da757-0a83-4e90-8547-22e3b52f7a2c.png)

# Testing Instructions
Manually or via bulkrax, create a work with child works. 
On the catalog page, search for metadata that exists on a parent work but not its children.
  - you will probably need to replicate this by editing the parent metadata directly, with a unique input. 
From the catalog page, search for that unique word. The parent work should return. 
Click into the parent work. It should auto perform a search in the UV.
  - before this would immediately result in a no matches found error
  - We don't want to see that error because there actually is a match on the parent. 
  - [ ] The parent's thumbnail (in the UV's left pane) should be highlighted with a blue box and magnifying class, if a match is found. 
 
Perform a bogus UV search (one that should not result in a match). 
  - [ ] we should see a no matches error msg
# Notes

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshots.

tested on:
- parent work: https://dcadmin-test.dlib.indiana.edu/concern/scientifics/st74cq441?locale=en&parent_query=tran

<details><summary>Searching for a parent work's metadata in the catalog leads to an auto-UV search for the query. Conducting a bogus search leads to an error message (correct).</summary>

![Scientific parent work ID st74cq441 Digital Collections 2023-05-10 at 12 46 06 PM](https://github.com/scientist-softserv/essi/assets/29311858/ddfb38ca-d777-4e35-bcb6-3bfe161008a2)
![Scientific parent work ID st74cq441 Digital Collections 2023-05-10 at 12 45 46 PM](https://github.com/scientist-softserv/essi/assets/29311858/46b0e648-b865-403b-91c4-f738e90cb1e3)

</details>
