### ISSUE TITLE
ESSI: PDF Split should not be configured anywhere

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/essi#9]
### Descriptive summary

The client does not want PDF Split. This ticket is to ensure that none of the models have it configured, per the 4/7/23 [client meeting.](https://docs.google.com/document/d/11gkrraG8xaDVro1F1uQu5bb3dQRQft6m14vt5fNYnFY/edit#)

### Rationale

PDF Splitting was never a desired feature

### ACCEPTANCE CRITERIA

When importing a PDF, it should NOT split into child works.

### Testing Instructions
- create any work type
- attach a multi page PDF file to it and save
- Go to the work's show page. Scroll down to the Items section. After sidekiq is done, the pdf should be available but there should be NOT child works created from it. With iiif_print, if enabled, there would be a child work for each page of the PDF. 

**sample file**: [iiif-print-test.pdf](https://github.com/scientist-softserv/essi/files/11180892/iiif-print-test.pdf)

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshot.

tested on:
- https://dcadmin-test.dlib.indiana.edu/concern/archival_materials/pk02c9724?locale=en
- sample file: [service-rbc-rbc0001-2015-2015gen56010-2015gen56010.pdf](https://github.com/scientist-softserv/essi/files/11445513/service-rbc-rbc0001-2015-2015gen56010-2015gen56010.pdf)

<details><summary>This multipage PDF did not split into child works</summary>

![Archival Material 2023-05-10 pdf splitting should not work ID pk02c9724 Digital Collections 2023-05-10 at 12 53 52 PM](https://github.com/scientist-softserv/essi/assets/29311858/af79e964-1ae4-4d0b-9592-77fb0ea701e5)
</details>

**Comment by jillpe** [comment]
closed - already present in essi
